### ISSUE TITLE
Option to have ResLogger2 open during cutscenes?

### ISSUE THREAD

**Issue by Sophira** [lmcintyre/ResLogger2#3]
First off, thanks for making this plugin - it seems like an incredibly useful tool!

I'd like to be able to do machinima with an animation that's used in one of the FFXIV cutscenes, using ResLogger2 to try to find the animation being loaded. However, when I use the Unending Journey to play the cutscene I want, ResLogger2 closes and typing `/reslog` in the chat during the cutscene doesn't bring it back.

I get that most people will not want ResLogger2 open during cutscenes, but it'd be really useful to me to be able to have an option for that if possible!

**Comment by lmcintyre** [comment]
You can disable Dalamud's UI hiding functionality when in cutscenes in the
Look and Feel tab of Dalamud settings.

**Comment by Sophira** [comment]
Ah, thank you! That did indeed help. Apologies for the inconvenience!
